/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    episodes: Episode;
    conversations: Conversation;
    workflows: Workflow;
    'activity-logs': ActivityLog;
    'export-jobs': ExportJob;
    departments: Department;
    agents: Agent;
    'custom-tools': CustomTool;
    'agent-executions': AgentExecution;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    episodes: EpisodesSelect<false> | EpisodesSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    workflows: WorkflowsSelect<false> | WorkflowsSelect<true>;
    'activity-logs': ActivityLogsSelect<false> | ActivityLogsSelect<true>;
    'export-jobs': ExportJobsSelect<false> | ExportJobsSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    agents: AgentsSelect<false> | AgentsSelect<true>;
    'custom-tools': CustomToolsSelect<false> | CustomToolsSelect<true>;
    'agent-executions': AgentExecutionsSelect<false> | AgentExecutionsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * Project ID reference
   */
  project: string;
  mediaType?:
    | (
        | 'style_reference'
        | 'character_design'
        | 'environment_design'
        | 'concept_art'
        | 'storyboard'
        | 'video_segment'
        | 'audio_clip'
        | 'voice_profile'
        | 'music_track'
        | 'sound_effect'
        | 'final_video'
      )
    | null;
  /**
   * Whether this media was generated by an AI agent
   */
  agentGenerated?: boolean | null;
  generationMetadata?: {
    /**
     * ID of the agent that generated this media
     */
    agentId?: string | null;
    /**
     * Prompt used for generation
     */
    promptUsed?: string | null;
    /**
     * Version of the AI model used
     */
    modelVersion?: string | null;
    generationTime?: string | null;
    /**
     * Background task ID for tracking
     */
    taskId?: string | null;
  };
  /**
   * Jina v4 multimodal embedding vector
   */
  embedding?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Human or AI-generated description of the media
   */
  description?: string | null;
  /**
   * Array of tags for categorization
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  relatedElements?: {
    /**
     * Character IDs featured in this media
     */
    characters?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    /**
     * Episode number if applicable
     */
    episode?: number | null;
    /**
     * Scene identifier if applicable
     */
    scene?: string | null;
    /**
     * Timestamp in seconds for video segments
     */
    timestamp?: number | null;
  };
  technicalData?: {
    /**
     * Duration in seconds for audio/video
     */
    duration?: number | null;
    /**
     * Resolution (e.g., 1920x1080)
     */
    resolution?: string | null;
    /**
     * Frames per second
     */
    fps?: number | null;
    /**
     * Audio sample rate in Hz
     */
    sampleRate?: number | null;
  };
  /**
   * Version number for iterative improvements
   */
  version?: number | null;
  status?: ('active' | 'draft' | 'archived' | 'processing' | 'failed') | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  /**
   * Auto-generated from name (URL-safe)
   */
  slug: string;
  type?: ('movie' | 'series') | null;
  /**
   * For movies
   */
  targetLength?: number | null;
  /**
   * For series
   */
  targetEpisodes?: number | null;
  genre?:
    | {
        genre?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * One-sentence pitch
   */
  logline?: string | null;
  synopsis?: string | null;
  targetAudience?: string | null;
  /**
   * e.g., PG-13, R, TV-MA
   */
  contentRating?: string | null;
  /**
   * Original concept/pitch
   */
  initialIdea?: string | null;
  storyPremise?: string | null;
  themes?:
    | {
        theme?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g., dark, comedic, dramatic
   */
  tone?: string | null;
  phase?: ('expansion' | 'compacting' | 'complete') | null;
  status?: ('active' | 'paused' | 'archived' | 'complete') | null;
  /**
   * 0-100
   */
  expansionProgress?: number | null;
  /**
   * 0-100
   */
  compactingProgress?: number | null;
  /**
   * 0-1 scale
   */
  overallQuality?: number | null;
  qualityBreakdown?: {
    story?: number | null;
    characters?: number | null;
    visuals?: number | null;
    technical?: number | null;
  };
  /**
   * Project creator/owner
   */
  owner: string | User;
  team?:
    | {
        user: string | User;
        role: 'owner' | 'editor' | 'collaborator' | 'viewer' | 'producer' | 'director' | 'writer';
        permissions?:
          | {
              permission?: string | null;
              id?: string | null;
            }[]
          | null;
        addedBy?: (string | null) | User;
        addedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Set if this project was cloned from another
   */
  clonedFrom?: {
    projectId?: (string | null) | Project;
    clonedAt?: string | null;
    clonedBy?: (string | null) | User;
  };
  settings?: {
    brainValidationRequired?: boolean | null;
    minQualityThreshold?: number | null;
    autoGenerateImages?: boolean | null;
    /**
     * e.g., RunwayML, Pika Labs
     */
    videoGenerationProvider?: string | null;
    maxBudget?: number | null;
  };
  /**
   * Auto-generated: open_[slug]
   */
  openDatabaseName: string;
  /**
   * List of created collections in open database
   */
  dynamicCollections?:
    | {
        collectionName?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  coverImage?: (string | null) | Media;
  isPublic?: boolean | null;
  /**
   * Auto-updated on activity
   */
  lastActivityAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes".
 */
export interface Episode {
  id: string;
  name: string;
  /**
   * Parent project/series
   */
  project: string | Project;
  episodeNumber: number;
  /**
   * Optional season number
   */
  seasonNumber?: number | null;
  /**
   * Official episode title
   */
  title?: string | null;
  /**
   * One-sentence summary
   */
  logline?: string | null;
  /**
   * Full episode synopsis
   */
  synopsis?: string | null;
  /**
   * Expected runtime
   */
  targetLength?: number | null;
  status?: ('outlined' | 'scripted' | 'storyboarded' | 'generated' | 'complete') | null;
  /**
   * 0-1 scale
   */
  qualityRating?: number | null;
  /**
   * Episode act breakdown
   */
  actStructure?:
    | {
        actNumber: number;
        description?: string | null;
        /**
         * Number of scenes in this act
         */
        sceneCount?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: string;
  /**
   * Descriptive name for this conversation
   */
  name: string;
  /**
   * Associated project (optional)
   */
  project?: (string | null) | Project;
  /**
   * Conversation owner
   */
  user?: (string | null) | User;
  /**
   * Conversation message history
   */
  messages?:
    | {
        /**
         * Unique message identifier
         */
        id: string;
        role: 'user' | 'assistant' | 'system';
        content: string;
        timestamp: string;
        /**
         * ID of the agent that generated this message
         */
        agentId?: string | null;
      }[]
    | null;
  status?: ('active' | 'archived') | null;
  /**
   * Timestamp of last message
   */
  lastMessageAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows".
 */
export interface Workflow {
  id: string;
  /**
   * Descriptive workflow name
   */
  name: string;
  /**
   * Associated project
   */
  project: string | Project;
  /**
   * Current production phase
   */
  currentPhase?: ('expansion' | 'compacting' | 'complete') | null;
  /**
   * Quality checkpoints and thresholds
   */
  qualityGates?:
    | {
        name: string;
        /**
         * 0-1 scale, minimum quality required to pass
         */
        threshold: number;
        /**
         * Whether this gate has been passed
         */
        passed?: boolean | null;
        /**
         * When this gate was last evaluated
         */
        evaluatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs".
 */
export interface ActivityLog {
  id: string;
  project: string | Project;
  user: string | User;
  action:
    | 'project.created'
    | 'project.updated'
    | 'project.deleted'
    | 'content.created'
    | 'content.updated'
    | 'content.deleted'
    | 'export.started'
    | 'export.completed'
    | 'team.member.added'
    | 'team.member.removed'
    | 'team.role.changed'
    | 'clone.created'
    | 'media.uploaded';
  /**
   * Type of entity affected (e.g., character, scene)
   */
  entityType?: string | null;
  /**
   * ID of the affected entity
   */
  entityId?: string | null;
  /**
   * Additional context about the action
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  timestamp: string;
  /**
   * User IP address
   */
  ipAddress?: string | null;
  /**
   * Browser user agent
   */
  userAgent?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "export-jobs".
 */
export interface ExportJob {
  id: string;
  jobId: string;
  project: string | Project;
  user: string | User;
  /**
   * ID of the video being exported
   */
  videoId: string;
  format: 'mp4' | 'webm' | 'mov';
  quality: 'low' | 'medium' | 'high' | 'ultra';
  /**
   * e.g., 1920x1080
   */
  resolution: string;
  /**
   * Frames per second
   */
  fps: number;
  status: 'pending' | 'processing' | 'completed' | 'failed' | 'cancelled';
  progress: number;
  /**
   * URL of the exported file
   */
  outputUrl?: string | null;
  /**
   * File size in bytes
   */
  outputSize?: number | null;
  /**
   * Error details if job failed
   */
  errorMessage?: string | null;
  /**
   * Additional export options
   */
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Time taken to complete export
   */
  processingTime?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Movie production departments with AI agent coordination
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: string;
  /**
   * Unique identifier (e.g., "story", "character", "visual")
   */
  slug: string;
  /**
   * Display name (e.g., "Story Department")
   */
  name: string;
  /**
   * Purpose and responsibilities of this department
   */
  description: string;
  /**
   * Emoji or icon identifier (e.g., "📖", "👤")
   */
  icon?: string | null;
  /**
   * Hex color for UI (e.g., "#8B5CF6")
   */
  color?: string | null;
  /**
   * Execution order (1-10, lower = higher priority)
   */
  priority: number;
  /**
   * Whether this department is active
   */
  isActive?: boolean | null;
  /**
   * Core departments cannot be deleted (Story, Character, Visual, Video, Audio, Production)
   */
  coreDepartment?: boolean | null;
  /**
   * Enable gather check for this department
   */
  gatherCheck?: boolean | null;
  /**
   * Default model for agents in this department (e.g., "anthropic/claude-3.5-sonnet")
   */
  defaultModel?: string | null;
  /**
   * Maximum steps for agent execution
   */
  maxAgentSteps?: number | null;
  /**
   * Settings for department coordination and workflow
   */
  coordinationSettings?: {
    /**
     * Allow specialists to run in parallel
     */
    allowParallelExecution?: boolean | null;
    /**
     * All specialist outputs must be reviewed by department head
     */
    requiresDepartmentHeadReview?: boolean | null;
    /**
     * Minimum quality score (0-100) for approval
     */
    minQualityThreshold?: number | null;
    /**
     * Maximum retry attempts for failed executions
     */
    maxRetries?: number | null;
  };
  /**
   * Auto-tracked performance metrics
   */
  performance?: {
    totalExecutions?: number | null;
    successfulExecutions?: number | null;
    averageQualityScore?: number | null;
    averageExecutionTime?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * AI agents for movie production workflow
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents".
 */
export interface Agent {
  id: string;
  /**
   * Unique identifier (e.g., "story-head-001", "character-dialogue-specialist")
   */
  agentId: string;
  /**
   * Display name
   */
  name: string;
  /**
   * Agent role and capabilities
   */
  description: string;
  /**
   * Which department this agent belongs to
   */
  department: string | Department;
  /**
   * Is this the department head? (Only one per department)
   */
  isDepartmentHead?: boolean | null;
  /**
   * Model to use (e.g., "anthropic/claude-3.5-sonnet", "anthropic/claude-3-opus")
   */
  model: string;
  /**
   * Core system prompt defining agent behavior and expertise
   */
  instructionsPrompt: string;
  /**
   * Custom tools this agent can use
   */
  toolNames?:
    | {
        toolName: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Maximum steps for this agent execution
   */
  maxAgentSteps?: number | null;
  /**
   * Specific area of expertise (e.g., "dialogue", "plot-structure", "character-arcs")
   */
  specialization?: string | null;
  /**
   * Specific skills for specialist selection
   */
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Is this agent active and available?
   */
  isActive?: boolean | null;
  /**
   * Auto-tracked performance data
   */
  performanceMetrics?: {
    successRate?: number | null;
    averageExecutionTime?: number | null;
    totalExecutions?: number | null;
    successfulExecutions?: number | null;
    failedExecutions?: number | null;
    averageQualityScore?: number | null;
    totalTokensUsed?: number | null;
  };
  /**
   * Last execution timestamp
   */
  lastExecutedAt?: string | null;
  /**
   * Does output need department head review? (Department heads must be false)
   */
  requiresReview?: boolean | null;
  /**
   * Minimum quality score (0-100) for approval
   */
  qualityThreshold?: number | null;
  executionSettings?: {
    /**
     * Maximum execution time in seconds
     */
    timeout?: number | null;
    /**
     * Maximum retry attempts on failure
     */
    maxRetries?: number | null;
    /**
     * Model temperature for creativity (0-2)
     */
    temperature?: number | null;
  };
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes for agent configuration
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reusable custom tools for AI agents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-tools".
 */
export interface CustomTool {
  id: string;
  /**
   * Unique identifier (e.g., "fetch-character-profile", "analyze-plot-structure")
   */
  toolName: string;
  /**
   * Human-readable name
   */
  displayName: string;
  /**
   * What this tool does and when to use it
   */
  description: string;
  /**
   * Zod schema as JSON defining tool inputs
   */
  inputSchema:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Example inputs for documentation and testing
   */
  exampleInputs?:
    | {
        example?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Expected output structure
   */
  outputSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * JavaScript/TypeScript function implementation
   */
  executeFunction: string;
  /**
   * Optional setup code (imports, initialization)
   */
  setupCode?: string | null;
  /**
   * Available to all agents across all departments
   */
  isGlobal?: boolean | null;
  /**
   * Departments that can use this tool (if not global)
   */
  departments?: (string | Department)[] | null;
  /**
   * Is this tool active and available?
   */
  isActive?: boolean | null;
  /**
   * Semantic version (e.g., 1.0.0)
   */
  version?: string | null;
  /**
   * Version history
   */
  changelog?:
    | {
        version: string;
        changes: string;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  dependencies?: {
    /**
     * Required NPM packages
     */
    npmPackages?:
      | {
          package: string;
          version?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * API keys needed for this tool
     */
    apiKeys?:
      | {
          keyName: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Other tools this tool depends on
     */
    otherTools?:
      | {
          toolName: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Auto-tracked usage metrics
   */
  performanceMetrics?: {
    totalCalls?: number | null;
    successfulCalls?: number | null;
    failedCalls?: number | null;
    averageExecutionTime?: number | null;
    lastUsedAt?: string | null;
  };
  /**
   * Test cases for validation
   */
  testCases?:
    | {
        name: string;
        input:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        expectedOutput?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        shouldFail?: boolean | null;
        id?: string | null;
      }[]
    | null;
  documentation?: {
    /**
     * How to use this tool
     */
    usage?: string | null;
    /**
     * Usage examples
     */
    examples?: string | null;
    /**
     * Known limitations
     */
    limitations?: string | null;
  };
  category?: ('data-retrieval' | 'analysis' | 'generation' | 'validation' | 'integration' | 'utility') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Tool creator
   */
  author?: (string | null) | User;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Agent execution tracking and audit trail
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-executions".
 */
export interface AgentExecution {
  id: string;
  /**
   * Unique execution identifier (auto-generated)
   */
  executionId: string;
  /**
   * Agent that executed this task
   */
  agent: string | Agent;
  /**
   * Department this execution belongs to
   */
  department: string | Department;
  /**
   * Project this execution is part of
   */
  project: string | Project;
  /**
   * Episode (if applicable)
   */
  episode?: (string | null) | Episode;
  /**
   * Link to conversation thread
   */
  conversationId?: string | null;
  /**
   * Parent execution if this is a sub-task
   */
  parentExecutionId?: string | null;
  /**
   * User or system prompt
   */
  prompt: string;
  /**
   * Additional execution parameters
   */
  params?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Agent output data
   */
  output?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Human-readable output text
   */
  outputText?: string | null;
  /**
   * Complete RunState from @codebuff/sdk
   */
  runState?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * All events during execution
   */
  events?:
    | {
        event?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'cancelled' | 'timeout';
  /**
   * Execution start time
   */
  startedAt?: string | null;
  /**
   * Execution completion time
   */
  completedAt?: string | null;
  /**
   * Total execution time in milliseconds
   */
  executionTime?: number | null;
  tokenUsage?: {
    inputTokens?: number | null;
    outputTokens?: number | null;
    totalTokens?: number | null;
    /**
     * Estimated cost in USD
     */
    estimatedCost?: number | null;
  };
  /**
   * Quality score (0-100)
   */
  qualityScore?: number | null;
  qualityBreakdown?: {
    accuracy?: number | null;
    completeness?: number | null;
    coherence?: number | null;
    creativity?: number | null;
  };
  reviewStatus?: ('pending' | 'approved' | 'rejected' | 'revision-needed') | null;
  /**
   * Department head or reviewer
   */
  reviewedBy?: (string | null) | Agent;
  /**
   * Reviewer feedback and notes
   */
  reviewNotes?: string | null;
  /**
   * Review timestamp
   */
  reviewedAt?: string | null;
  /**
   * Error information if execution failed
   */
  error?: {
    message?: string | null;
    code?: string | null;
    stack?: string | null;
    details?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  /**
   * Number of retry attempts
   */
  retryCount?: number | null;
  /**
   * Maximum retry attempts allowed
   */
  maxRetries?: number | null;
  /**
   * All tool calls made during execution
   */
  toolCalls?:
    | {
        toolName: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        executionTime?: number | null;
        success?: boolean | null;
        error?: string | null;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'episodes';
        value: string | Episode;
      } | null)
    | ({
        relationTo: 'conversations';
        value: string | Conversation;
      } | null)
    | ({
        relationTo: 'workflows';
        value: string | Workflow;
      } | null)
    | ({
        relationTo: 'activity-logs';
        value: string | ActivityLog;
      } | null)
    | ({
        relationTo: 'export-jobs';
        value: string | ExportJob;
      } | null)
    | ({
        relationTo: 'departments';
        value: string | Department;
      } | null)
    | ({
        relationTo: 'agents';
        value: string | Agent;
      } | null)
    | ({
        relationTo: 'custom-tools';
        value: string | CustomTool;
      } | null)
    | ({
        relationTo: 'agent-executions';
        value: string | AgentExecution;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  project?: T;
  mediaType?: T;
  agentGenerated?: T;
  generationMetadata?:
    | T
    | {
        agentId?: T;
        promptUsed?: T;
        modelVersion?: T;
        generationTime?: T;
        taskId?: T;
      };
  embedding?: T;
  description?: T;
  tags?: T;
  relatedElements?:
    | T
    | {
        characters?: T;
        episode?: T;
        scene?: T;
        timestamp?: T;
      };
  technicalData?:
    | T
    | {
        duration?: T;
        resolution?: T;
        fps?: T;
        sampleRate?: T;
      };
  version?: T;
  status?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  targetLength?: T;
  targetEpisodes?: T;
  genre?:
    | T
    | {
        genre?: T;
        id?: T;
      };
  logline?: T;
  synopsis?: T;
  targetAudience?: T;
  contentRating?: T;
  initialIdea?: T;
  storyPremise?: T;
  themes?:
    | T
    | {
        theme?: T;
        id?: T;
      };
  tone?: T;
  phase?: T;
  status?: T;
  expansionProgress?: T;
  compactingProgress?: T;
  overallQuality?: T;
  qualityBreakdown?:
    | T
    | {
        story?: T;
        characters?: T;
        visuals?: T;
        technical?: T;
      };
  owner?: T;
  team?:
    | T
    | {
        user?: T;
        role?: T;
        permissions?:
          | T
          | {
              permission?: T;
              id?: T;
            };
        addedBy?: T;
        addedAt?: T;
        id?: T;
      };
  clonedFrom?:
    | T
    | {
        projectId?: T;
        clonedAt?: T;
        clonedBy?: T;
      };
  settings?:
    | T
    | {
        brainValidationRequired?: T;
        minQualityThreshold?: T;
        autoGenerateImages?: T;
        videoGenerationProvider?: T;
        maxBudget?: T;
      };
  openDatabaseName?: T;
  dynamicCollections?:
    | T
    | {
        collectionName?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  coverImage?: T;
  isPublic?: T;
  lastActivityAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "episodes_select".
 */
export interface EpisodesSelect<T extends boolean = true> {
  name?: T;
  project?: T;
  episodeNumber?: T;
  seasonNumber?: T;
  title?: T;
  logline?: T;
  synopsis?: T;
  targetLength?: T;
  status?: T;
  qualityRating?: T;
  actStructure?:
    | T
    | {
        actNumber?: T;
        description?: T;
        sceneCount?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  name?: T;
  project?: T;
  user?: T;
  messages?:
    | T
    | {
        id?: T;
        role?: T;
        content?: T;
        timestamp?: T;
        agentId?: T;
      };
  status?: T;
  lastMessageAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows_select".
 */
export interface WorkflowsSelect<T extends boolean = true> {
  name?: T;
  project?: T;
  currentPhase?: T;
  qualityGates?:
    | T
    | {
        name?: T;
        threshold?: T;
        passed?: T;
        evaluatedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-logs_select".
 */
export interface ActivityLogsSelect<T extends boolean = true> {
  project?: T;
  user?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  metadata?: T;
  timestamp?: T;
  ipAddress?: T;
  userAgent?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "export-jobs_select".
 */
export interface ExportJobsSelect<T extends boolean = true> {
  jobId?: T;
  project?: T;
  user?: T;
  videoId?: T;
  format?: T;
  quality?: T;
  resolution?: T;
  fps?: T;
  status?: T;
  progress?: T;
  outputUrl?: T;
  outputSize?: T;
  errorMessage?: T;
  options?: T;
  startedAt?: T;
  completedAt?: T;
  processingTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  description?: T;
  icon?: T;
  color?: T;
  priority?: T;
  isActive?: T;
  coreDepartment?: T;
  gatherCheck?: T;
  defaultModel?: T;
  maxAgentSteps?: T;
  coordinationSettings?:
    | T
    | {
        allowParallelExecution?: T;
        requiresDepartmentHeadReview?: T;
        minQualityThreshold?: T;
        maxRetries?: T;
      };
  performance?:
    | T
    | {
        totalExecutions?: T;
        successfulExecutions?: T;
        averageQualityScore?: T;
        averageExecutionTime?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agents_select".
 */
export interface AgentsSelect<T extends boolean = true> {
  agentId?: T;
  name?: T;
  description?: T;
  department?: T;
  isDepartmentHead?: T;
  model?: T;
  instructionsPrompt?: T;
  toolNames?:
    | T
    | {
        toolName?: T;
        id?: T;
      };
  maxAgentSteps?: T;
  specialization?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  isActive?: T;
  performanceMetrics?:
    | T
    | {
        successRate?: T;
        averageExecutionTime?: T;
        totalExecutions?: T;
        successfulExecutions?: T;
        failedExecutions?: T;
        averageQualityScore?: T;
        totalTokensUsed?: T;
      };
  lastExecutedAt?: T;
  requiresReview?: T;
  qualityThreshold?: T;
  executionSettings?:
    | T
    | {
        timeout?: T;
        maxRetries?: T;
        temperature?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-tools_select".
 */
export interface CustomToolsSelect<T extends boolean = true> {
  toolName?: T;
  displayName?: T;
  description?: T;
  inputSchema?: T;
  exampleInputs?:
    | T
    | {
        example?: T;
        id?: T;
      };
  outputSchema?: T;
  executeFunction?: T;
  setupCode?: T;
  isGlobal?: T;
  departments?: T;
  isActive?: T;
  version?: T;
  changelog?:
    | T
    | {
        version?: T;
        changes?: T;
        date?: T;
        id?: T;
      };
  dependencies?:
    | T
    | {
        npmPackages?:
          | T
          | {
              package?: T;
              version?: T;
              id?: T;
            };
        apiKeys?:
          | T
          | {
              keyName?: T;
              description?: T;
              id?: T;
            };
        otherTools?:
          | T
          | {
              toolName?: T;
              id?: T;
            };
      };
  performanceMetrics?:
    | T
    | {
        totalCalls?: T;
        successfulCalls?: T;
        failedCalls?: T;
        averageExecutionTime?: T;
        lastUsedAt?: T;
      };
  testCases?:
    | T
    | {
        name?: T;
        input?: T;
        expectedOutput?: T;
        shouldFail?: T;
        id?: T;
      };
  documentation?:
    | T
    | {
        usage?: T;
        examples?: T;
        limitations?: T;
      };
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "agent-executions_select".
 */
export interface AgentExecutionsSelect<T extends boolean = true> {
  executionId?: T;
  agent?: T;
  department?: T;
  project?: T;
  episode?: T;
  conversationId?: T;
  parentExecutionId?: T;
  prompt?: T;
  params?: T;
  output?: T;
  outputText?: T;
  runState?: T;
  events?:
    | T
    | {
        event?: T;
        id?: T;
      };
  status?: T;
  startedAt?: T;
  completedAt?: T;
  executionTime?: T;
  tokenUsage?:
    | T
    | {
        inputTokens?: T;
        outputTokens?: T;
        totalTokens?: T;
        estimatedCost?: T;
      };
  qualityScore?: T;
  qualityBreakdown?:
    | T
    | {
        accuracy?: T;
        completeness?: T;
        coherence?: T;
        creativity?: T;
      };
  reviewStatus?: T;
  reviewedBy?: T;
  reviewNotes?: T;
  reviewedAt?: T;
  error?:
    | T
    | {
        message?: T;
        code?: T;
        stack?: T;
        details?: T;
      };
  retryCount?: T;
  maxRetries?: T;
  toolCalls?:
    | T
    | {
        toolName?: T;
        input?: T;
        output?: T;
        executionTime?: T;
        success?: T;
        error?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}